### ISSUE TITLE
Add k2pow calculation to the profiler

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/post-rs#108]
I think we should add a basic unit (64nonces 256GiB) benchmark to the profiler tool.

Now it's missing and could result in someone initializing too much.

**Comment by poszu** [comment]
The goal of the profiler is to help users decide about two things:
- how much storage they can initialize to be able to create a POST proof on time,
- how to configure _threads_ and _parallel nonces_ to get the best results (equally stress disk and CPU).

The k2 proof of work is unrelated to the second bullet point and hence I would leave the option to just run raw data reading speed benchmark as an option for those who already know the impact of PoW and just want to fine-tune _threads_ and _nonces_.

💡 We need to also keep in mind that just initializing a RandomX VM takes ~20-30s. It would be a huge slowdown to do it every time.

Let's think what's the best API to select mode of operation (with/without k2pow). How is it going to be used from Smapp?

IMHO, given the long RandomX init duration, a k2pow benchmark should be a separate command, not executed in the "data read speed" benchmark.

**Comment by pigmej** [comment]
I'd definitely split that from main profiler call for the reasons that you mentioned.

I think API like:
`./prifiler -k2pow -units 10 -nonces 128`  would be ok and then basically do the math to land on these units from 256 and 64 bases.
