### ISSUE TITLE
help for  verify error data

### ISSUE THREAD

**Issue by robotchangzhang** [spacemeshos/post-rs#117]
ERROR    636ff.post    Proof is invalid: MSB value for index: 117717007989 doesn't satisfy difficulty: 215 > 0 (label: [145, 107, 182, 205, 188, 156, 238, 115, 148, 20, 39, 181, 44, 4, 119, 80])    {"node_id": "", "module": "post", "module": "post::post_impl", "file": "ffi\src\post_impl.rs", "line": 242}

initial POST proof is invalid. Probably the initialized POST data is corrupted. Please verify the data with postcli and regenerate the corrupted files

I find this code:
(https://github.com/spacemeshos/post-rs/blob/main/ffi/src/post_impl.rs#L239)

and I want  this code tell me which postdata file is error

**Comment by poszu** [comment]
Closing as stale. @robotchangzhang, please reopen if you still have the problem.
