### ISSUE TITLE
Profiler does not seem to work correctly on Linux amd64

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/post-rs#72]
cmdline:
```
time ./profiler --k2-pow-difficulty 891576961504 --data-file profiler_data.bin --data-size 1 --duration 10 -t 1
^C

real	5m3.591s
user	76m50.815s
sys	0m5.756s
```

There is also 0 data created on the disk despite running for 5mins (instead of 10seconds as I asked)

Additionally, there was nothing created on a disk. Screenshot presents CPU usage
![image (3)](https://github.com/spacemeshos/post-rs/assets/496754/456ef6d2-0224-4a8e-bf38-de6b48b4588b)

When I removed `--k2-pow-difficulty 891576961504` from the cmdline then it started to behave ok.

```
root@testnet-04-miner-1-0:~/data/post/profiler_d# time ./profiler  --data-file profiler_data.bin --data-size 1 --duration 10 -t 1
{
  "time_s": 10.6147993,
  "speed_gib_s": 0.9420809303478777
}

real	0m10.644s
user	0m9.243s
sys	0m1.402s
```

**Comment by poszu** [comment]
It's doing K2 proof of work first, for which it uses all cores (not respecting the passed `-t 1` - #74). Besides that IMO it works OK.
